/**
 * COPYRIGHT INFORMATION HERE
 * 
 * THIS IS A SERVER ENGINE ACTING AS A PLUGINE FOR THE SERVER SIZE BOLT IN RPC COMMUNICATION
 */

#ifndef MIQS_RPC_SERVER_ENGINE_H
#define MIQS_RPC_SERVER_ENGINE_H

#ifdef MIQS_RPC_MPI_ENABLED
    #include "mpi.h"
#endif


#endif /* MIQS_RPC_SERVER_ENGINE_H */